[2024-07-17T12:28:50.876+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T12:28:50.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_airflow_dag.task1 manual__2024-07-16T18:39:36.345427+00:00 [queued]>
[2024-07-17T12:28:50.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_airflow_dag.task1 manual__2024-07-16T18:39:36.345427+00:00 [queued]>
[2024-07-17T12:28:50.910+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-07-17T12:28:50.923+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task1> on 2024-07-16 18:39:36.345427+00:00
[2024-07-17T12:28:50.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T12:28:50.930+0000] {standard_task_runner.py:64} INFO - Started process 245 to run task
[2024-07-17T12:28:50.930+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_***_dag', 'task1', 'manual__2024-07-16T18:39:36.345427+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpuqnmyafx']
[2024-07-17T12:28:50.931+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask task1
[2024-07-17T12:28:50.978+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_airflow_dag.task1 manual__2024-07-16T18:39:36.345427+00:00 [running]> on host 8f6756dc8ee6
[2024-07-17T12:28:51.066+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_***_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T18:39:36.345427+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T18:39:36.345427+00:00'
[2024-07-17T12:28:51.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T12:28:51.068+0000] {logging_mixin.py:188} INFO - Error during unarchive: [Errno 2] No such file or directory: '/Users/pro/downloads/Data.zip'
[2024-07-17T12:28:51.069+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T12:28:51.069+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_dag.py", line 59, in unarchive
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1331, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pro/downloads/Data.zip'
[2024-07-17T12:28:51.080+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=simple_***_dag, task_id=task1, run_id=manual__2024-07-16T18:39:36.345427+00:00, execution_date=20240716T183936, start_date=20240717T122850, end_date=20240717T122851
[2024-07-17T12:28:51.092+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task task1 ([Errno 2] No such file or directory: '/Users/pro/downloads/Data.zip'; 245)
[2024-07-17T12:28:51.112+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-17T12:28:51.138+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T12:28:51.186+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
